### ISSUE TITLE
It's an error and I can't output. (エラーが出て書き出せない)

### ISSUE THREAD

**Issue by f-fukuhara** [qjebbs/sketch-meaxure#1]
プラグインの作成ありがとうございます！
相談なのですが、
Text Style の設定された Symbol を配置していると以下のエラーが出て書き出せません。

<img width="420" alt="Error" src="https://user-images.githubusercontent.com/63627611/79187619-c0caeb80-7e57-11ea-8b51-fda85816b0f9.png">

テキストを打ち直すと書き出せるようになりますが、Sample.sketch を添付しますのでご確認いただけますでしょうか？

----
Thank you for creating the plugin!
I'd like to consult with you.
The following error occurs when I place the Symbol which is set in Text Style, and it cannot be written out.

<img width="420" alt="Error" src="https://user-images.githubusercontent.com/63627611/79187619-c0caeb80-7e57-11ea-8b51-fda85816b0f9.png">

I am attaching the sample.sketch so that you can check it.

[Sample.sketch.zip](https://github.com/qjebbs/sketch-meaxure/files/4473223/Sample.sketch.zip)

**Comment by qjebbs** [comment]
Confirmed. Please try the latest release.

**Comment by f-fukuhara** [comment]
@qjebbs 

早々に対応してくれてありがとうございます！助かります！
最新のリリースで書き出すことができました！
(でも私のデータでは別のエラーがいくつか出てきたので、問題点を確認して issue あげますね 😢)

----

Thank you for being so quick to respond! Thank you so much!
I was able to write it out in the latest release!
(But I've seen some other errors in my data, so I'll check and issue the problem 😢)

**Comment by qjebbs** [comment]
Of course, any feedback is welcome
