### ISSUE TITLE
组包含控件，当组设置为切图，导出后assets里该控件图为透明

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#10]
![image](https://user-images.githubusercontent.com/25951301/84340249-d7c95800-abd2-11ea-96b2-eb8fab73c8fe.png)
![image](https://user-images.githubusercontent.com/25951301/84340165-a18bd880-abd2-11ea-8b08-37b9bf6d0fc1.png)
![image](https://user-images.githubusercontent.com/25951301/84340182-b10b2180-abd2-11ea-8a40-1ba7f42da8a4.png)
![image](https://user-images.githubusercontent.com/25951301/84340195-ba948980-abd2-11ea-8bb8-42c7921ad2dc.png)

样本：
[test.zip](https://github.com/qjebbs/sketch-meaxure/files/4762344/test.zip)

**Comment by uncleLian** [comment]
这个fix导致了另外的问题

**Comment by uncleLian** [comment]
![image](https://user-images.githubusercontent.com/25951301/84357650-9d72b180-abf8-11ea-95ab-5daac72b87fb.png)

**Comment by uncleLian** [comment]
该画板引用symbol时，不能正确导出
![image](https://user-images.githubusercontent.com/25951301/84357798-d01caa00-abf8-11ea-9b83-5dfc84431044.png)
![image](https://user-images.githubusercontent.com/25951301/84358019-17a33600-abf9-11ea-9ad9-806934d4c1f1.png)

**Comment by qjebbs** [comment]
You need provide a sample to reproduce this issue

**Comment by uncleLian** [comment]
[sample.zip](https://github.com/qjebbs/sketch-meaxure/files/4763331/sample.zip)
