### ISSUE TITLE
Multi Layers export spec stuck

### ISSUE THREAD

**Issue by fengqinglingyu** [qjebbs/sketch-meaxure#11]
I've got a sketch file which contain 1135 layers, when I tried to export, it took about 420 seconds to finish it, while it only took about 4 seconds in Sketch Measure.
I tried to solve the problem.
I found that the method  updateMaskStackAfterLayer take a lot of time, then I locate that the problem was from  the method named allSubLayers. 
here are my solution:

```ts
// src/meaxure/export/mask.ts
-            groupLayers = lastLayer.allSubLayers();
-            lastLayer = groupLayers[groupLayers.length - 1];
+           lastLayer = lastLayer.getLastLayer();
```
```ts
// src/sketch/layer/index.ts
    target.getLastLayer = function () : Layer {
        let layer = this;
        while(layer.layers) {
            layer = layer.layers[layer.layers.length - 1]
        }
        return layer;
    }
```
After I've update it , it took only 10 seconds to export.
Maybe is the recursion in allSubLayers causes the problem? I want to see how you solve the problem.

**Comment by fengqinglingyu** [comment]
here is the examle:
[test.sketch.zip](https://github.com/qjebbs/sketch-meaxure/files/4763450/test.sketch.zip)

**Comment by qjebbs** [comment]
Good point & good exsample, Thanks!
