### ISSUE TITLE
如何以插件层级存储配置？

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#13]
我在ConfigsMaster方法里面使用对应的 settingForKey， setSettingForKey，在导入JSON文件后使用setSettingForKey设置值xx，然后立刻输出context.configs.xx 并不能得到正确的值。setSettingForKey是否是异步？或者ConfigsMaster 就是以document层级来存储配置的？我应该怎么实现插件层级存储配置？

**Comment by qjebbs** [comment]
You should turn to [Sketch JavaScript API](https://developer.sketch.com/reference/api).
