### ISSUE TITLE
标注页没有正确显示symbol的名称

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#16]
![image](https://user-images.githubusercontent.com/25951301/87746095-4dec5a80-c822-11ea-8b32-82a1922c9916.png)
![image](https://user-images.githubusercontent.com/25951301/87746170-7bd19f00-c822-11ea-8a31-87b38312ecaf.png)
![image](https://user-images.githubusercontent.com/25951301/87746103-5349a500-c822-11ea-8066-5171cad12183.png)

样本：
[symbol_name_bug.zip](https://github.com/qjebbs/sketch-meaxure/files/4935611/symbol_name_bug.zip)

**Comment by qjebbs** [comment]
It's not a bug.  

Layer `HELLO` (on top) has exactly the same size & position, with its parent `标题` (bottom)，so you can only select the `HELLO`, and never the `标题`,  it of coursesays `HELLO`. 

Same happens to `文案` and `落地页标题`

**Comment by uncleLian** [comment]
measure 可以正常显示`落地页标题`，但其他一样显示`HELLO`，希望能做到measure的效果

![image](https://user-images.githubusercontent.com/25951301/87771293-be12d480-c852-11ea-877e-997925585131.png)
