### ISSUE TITLE
I can't export when different colors are mixed in the text box. (テキストボックスの中に違う色が混ざると書き出せない)

### ISSUE THREAD

**Issue by f-fukuhara** [qjebbs/sketch-meaxure#2]
テキストボックスの中に、下の画像のように異なる色の設定をしたテキストが混ざっていると
書き出せません...😢
<img width="347" alt="textbox" src="https://user-images.githubusercontent.com/63627611/79301587-eb36aa80-7f24-11ea-903c-b940e9b9a6c4.png">

文言によって異なるエラーがでますが、
同じの文字色に変更すればどちらも書き出せるようになります。

異なるエラーが出る理由が不明なのですが、2種類のアートボードを作成したので
それぞれご確認いただけますでしょうか？

Sample アートボードでは以下のエラーがでて、
<img width="421" alt="Sample_Error" src="https://user-images.githubusercontent.com/63627611/79301714-381a8100-7f25-11ea-800d-0ba05e8e609c.png">

Samle2 アートボードでは以下のエラーがでます。
<img width="423" alt="Sample2_Error" src="https://user-images.githubusercontent.com/63627611/79301770-5ed8b780-7f25-11ea-99fc-b7c040a4095b.png">

ご確認ください。

----

If the text box contains text with different color settings, as shown in the image below, the
I can't be exported ... 😢
<img width="347" alt="textbox" src="https://user-images.githubusercontent.com/63627611/79301587-eb36aa80-7f24-11ea-903c-b940e9b9a6c4.png">

Different wording gives different errors, but
If you change to the same font color, both can be exported.

I'm not sure why I'm getting different errors, but I've created two different artboards
Would you be able to confirm each one?

The following error occurs on the Sample artboard
<img width="421" alt="Sample_Error" src="https://user-images.githubusercontent.com/63627611/79301714-381a8100-7f25-11ea-800d-0ba05e8e609c.png">

I get the following error on the Samle2 artboard.
<img width="423" alt="Sample2_Error" src="https://user-images.githubusercontent.com/63627611/79301770-5ed8b780-7f25-11ea-99fc-b7c040a4095b.png">

Please check it out.

[Sample.sketch.zip](https://github.com/qjebbs/sketch-meaxure/files/4479266/Sample.sketch.zip)

**Comment by qjebbs** [comment]
Thanks. Please try the latest release.

**Comment by f-fukuhara** [comment]
@qjebbs 

ありがとうございます！
最新のリリースで無事書き出すことができました！
助かります！🙌

----
<< English description follows Japanese >> 

Thank you so much!
I was able to be exported successfully with the latest release!
🙌
