### ISSUE TITLE
notes inside symbols can not be hidden when export spec

### ISSUE THREAD

**Issue by linlinlincom** [qjebbs/sketch-meaxure#21]
![20200819113146](https://user-images.githubusercontent.com/69840769/90589079-cc685d80-e20f-11ea-8f1d-350c7b48056f.jpg)
notes should be hidden except hover on the numbers.

[测试备注放在symbol没有隐藏.zip](https://github.com/qjebbs/sketch-meaxure/files/5093868/symbol.zip)

**Comment by qjebbs** [comment]
Good point. You can hide it manually hide notes before next version released.
