### ISSUE TITLE
导出标注时，部分资源无法导出

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#22]
问题：组件只有一部分在画板中。导出标注时，只有该部分的切图被导出。没有将该组件全部切图导出。
期望：导出该组件所有切图资源

![image](https://user-images.githubusercontent.com/25951301/92203607-245fbf00-eeb4-11ea-93c7-8387927e0f71.png)
![image](https://user-images.githubusercontent.com/25951301/92203744-802a4800-eeb4-11ea-841d-eba2fd11ea18.png)

这是measure导出的。

![image](https://user-images.githubusercontent.com/25951301/92203753-84566580-eeb4-11ea-912f-2a354e5a056a.png)

测试文件：
[test.sketch.zip](https://github.com/qjebbs/sketch-meaxure/files/5172903/test.sketch.zip)

**Comment by uncleLian** [comment]
发现3.2.1版本是正常的，是否和这个commit有关？
https://github.com/qjebbs/sketch-meaxure/commit/78ce60354be36e75f7029995ac2618914524c243

**Comment by qjebbs** [comment]
No. It's expected, no seeing, no exporting: 86755b312fa6e0391f699505b0417329de8f5a7a

**Comment by qjebbs** [comment]
I want to keep exported tidy, small, targeted. You want layers, put them inside the artboard, make the artboard bigger sometimes.
