### ISSUE TITLE
May I join you

### ISSUE THREAD

**Issue by hubzy** [qjebbs/sketch-meaxure#23]
Hello
In my spare time, I did some optimization on the plug-in.
Waterfall flow Preview
Black and white skin switch
Resources can be downloaded directly
Click copy code
Style optimization
Shortcut key compatible processing, user habit modification
... 

I hope I can help more people
I'm a UI designer by profession

My Project preview

**Comment by qjebbs** [comment]
What do you mean by 'join me'? 

- If you wan to contribute, please submit PRs. 
- If you want to join as an collaborator, and have direct access to this repo, we need to talk 🤝
