### ISSUE TITLE
tint color 没有正确显示

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#24]
首先感谢你在图层解析的时候考虑到了tint颜色，但现在有一些问题。

场景：layer是group的时候可以正确显示tint颜色，但symbol的时候不能

期望：symbol也能正确显示tint颜色

![image](https://user-images.githubusercontent.com/25951301/93593585-f8c9f200-f9e6-11ea-8cc7-8a571cae7d27.png)

![image](https://user-images.githubusercontent.com/25951301/93593536-e3ed5e80-f9e6-11ea-803a-86706dd3f102.png)

Demo
[tintError.sketch.zip](https://github.com/qjebbs/sketch-meaxure/files/5245217/tintError.sketch.zip)

**Comment by qjebbs** [comment]
Good one 👍
