### ISSUE TITLE
网站同时发送2个相同meaxure.postMessage会导致其中一个超时没有响应

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#27]
例如代码：
// sketch
panel.onDidReceiveMessage('token', () => data);
// web
const token = await meaxure.postMessage('token')
因为获取token方法我写在axios interceptors中，发起请求时会在拦截器里先获取token。当页面有多个请求同时发送的时候，导致meaxure.postMessage('token')请求超时无法响应，具体错误信息：Promise of client request not resolved or rejected in 30 seconds. 
目前解决方案是使用setTimout来阻止同时发送多个请求。这个问题有什么好的解决办法吗？

**Comment by qjebbs** [comment]
This is an irrelevant issue to this plugin, closing...

- `WebviewPanel` is just a inner package, it works just enough for the plugin, I 'm not going to maintain it for outer, broadly usage
- The only tip I can tell you, take a look at the init process of messaging
