### ISSUE TITLE
Object.keys Error

### ISSUE THREAD

**Issue by Nevu** [qjebbs/sketch-meaxure#28]
Hi!

When trying to export specs in some files I got this error message
Any tips?

<img width="424" alt="error-on-sketch69" src="https://user-images.githubusercontent.com/2456068/96088876-5a865a80-0ec6-11eb-8057-9ee6d064ae0d.png">

**Comment by qjebbs** [comment]
You'd better provider sketch file to reproduce it.

You can remove all other layers, just keep the part that lead to this issue, notice it's related to layer `Headline-Kachel`

**Comment by Nevu** [comment]
I've upload the isolated file. I guess it's something with the mixes typo?
[error.zip](https://github.com/qjebbs/sketch-meaxure/files/5433009/error.zip)

**Comment by qjebbs** [comment]
I cannot reproduce it with your file

**Comment by Nevu** [comment]
I tried again with this file.
It didn't worked.

It seems it have something to to with the mixed color in one textfield (black + red).
I will just keep Attention to that. Indeed you should build like this :)

**Comment by qjebbs** [comment]
https://github.com/sketch-hq/SketchAPI/issues/810
