### ISSUE TITLE
导出标注后出错问题

### ISSUE THREAD

**Issue by Daa1874** [qjebbs/sketch-meaxure#3]
首先感谢大佬更新了meaxure插件，让我能够在工作中减少很多时间。
在使用meaxure时遇到了一个问题，我使用mesxure标记的标注文本，导出时提示typeerror：undefined is not an object，请问这个有什么解决的办法吗？如方便，感谢解答。
sketch版本：63.1
meaxure版本：3.1.4
![image](https://user-images.githubusercontent.com/63888777/79625294-a7c58180-815a-11ea-99c0-167e6d3997e8.png)

**Comment by qjebbs** [comment]
You'd better provide a minimal sketch file which can reproduce this issue.

**Comment by Daa1874** [comment]
> 您最好提供一个可以重现此问题的最小草图文件。
请查收。

[标注BUG.zip](https://github.com/qjebbs/sketch-meaxure/files/4496371/BUG.zip)

**Comment by qjebbs** [comment]
<img width="254" alt="image" src="https://user-images.githubusercontent.com/16953333/79636048-9787c380-81a7-11ea-8805-3f26230b0e4d.png">

There is a malformed Text in your file, I don't know why. A normal Text layer will of course has text color property, while yours doesn't. Maybe it's from an old version, or a cracked version with unexpected behavior.

Choose `进行中`, reset it's color, you'll export well.

**Comment by Daa1874** [comment]
> <img alt="图片" width="254" src="https://user-images.githubusercontent.com/16953333/79636048-9787c380-81a7-11ea-8805-3f26230b0e4d.png">
> 
> 您的文件中有一个格式错误的文本，我不知道为什么。普通的Text图层当然会具有文本颜色属性，而您的则不会。
> 
> 选择`进行中`，重置其颜色，即可顺利导出。

十分感谢，我好像找到原因了，因为那个文字图层使用图形的填充效果，导致和文字本身的颜色重叠了，所以读取不到文字图层自身的颜色属性。
