### ISSUE TITLE
Error processing layer 验证身份即可查看. Error: splitFragment: fragment splitted to negtive length

### ISSUE THREAD

**Issue by Theal1** [qjebbs/sketch-meaxure#31]
Spec Export one Art board and it shows:

Error processing layer 验证身份即可查看. Error: splitFragment: fragment splitted to negtive length

Changed the problem layer name to ’YZ‘, all the same: 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/73679883/97655416-02dc1780-1aa0-11eb-8113-cb9109a2d0fc.png">

Sketch 69.1 (107496)

**Comment by qjebbs** [comment]
You'd better provider sketch file to reproduce it.

**Comment by Theal1** [comment]
Sure, please click this:
[Download Sketch file](http://theal.net/uploads/errorOnSpecExport.sketch)

Thanks for your prevenance

**Comment by Theal1** [comment]
And I tested the file above with Sketch 68.2 and Sketch Measure 2.8.1, which has no error. Looking forward to resolve this error. Thank you soooooooooooooooo  much 😘

**Comment by hubzy** [comment]
> 我使用Sketch 68.2和Sketch Measure 2.8.1测试了上面的文件，没有错误。期待解决此错误。太谢谢你了😘

一个文字图层多样式属性（颜色）引起的，建议不同属性区分不同图层
