### ISSUE TITLE
Download of Icon-Assets does not work (white, empty page)

### ISSUE THREAD

**Issue by baakoo** [qjebbs/sketch-meaxure#32]
Hi,

exportable assets are shown in the section but a click only shows an empty page. I can reproduce this with different Sketch files and on different Macs. A fix would be great

Cheers

**Comment by qjebbs** [comment]
pls try latest release to see if helps

**Comment by baakoo** [comment]
at least in my case it does not help?
I use meaxure 3.2.11
i tried Firefox and Safari -> Assets are listed, but when I open the asset, there is an empty page

**Comment by qjebbs** [comment]
cannot reproduce here

**Comment by lixiaojie-m** [comment]
hello
I encountered the problem of downloading assets, and clicking on the asset no longer has the page to select the asset format

**Comment by lixiaojie-m** [comment]
hello
I encountered the problem of downloading assets, and clicking on the asset no longer has the page to select the asset format
i use meaxure 3.31
sketch 69.2

**Comment by qjebbs** [comment]
@lixiaojie-m 

![image](https://user-images.githubusercontent.com/16953333/98884269-97943b80-24ca-11eb-83dc-96d0c147634e.png)

**Comment by baakoo** [comment]
The problem still exists here on different macs

**Comment by lixiaojie-m** [comment]
![image](https://user-images.githubusercontent.com/56859524/98902120-0c2da100-24f0-11eb-952a-bbb3d6110d41.png)
现在点击切图不再弹出此选择弹窗，而是新开了一个浏览页面，并且对切图进行右击保存的格式为webp格式

**Comment by qjebbs** [comment]
@lixiaojie-m  No, the plugin never provides such a page. You might be mixed up with other plugin or service.

**Comment by qjebbs** [comment]
@baakoo I cannot help you, if you cannot provides more informations.

**Comment by lixiaojie-m** [comment]
But now I can’t save the asset by clicking it,and Right-click can only save webp format

**Comment by qjebbs** [comment]
Don't you ever try different ways? 😂 Drag it to somewhere, or click to open new window and save it

**Comment by lixiaojie-m** [comment]
I have tried all the ways，
But none of the saved pictures are in the format I want

**Comment by lixiaojie-m** [comment]
要不加个微信吧，哈哈哈，每次更新前都可以帮你测
