### ISSUE TITLE
rem measurement

### ISSUE THREAD

**Issue by schokominzdrops** [qjebbs/sketch-meaxure#37]
Hi,
when I installed the plugin for Sketch, measurements in "rem" were possible. Since the last update I can't find this unit in the settings any more. Is there any other possibility to measure in rem or can you please integrate this unit again?
Thank you!

![Bildschirmfoto 2020-11-04 um 18 06 47](https://user-images.githubusercontent.com/73957869/98142827-99597000-1ec8-11eb-8436-d045d33d8ffa.png)

**Comment by qjebbs** [comment]
The scale& unit setting now represents design resolution, e.g.: `scale:1 unit:pt` means `1px on Sketch = 1pt on target device`.

In what case you want `1px on sketch = 1rem on device`?

PS: It's seems that the UI needs some tweak for the new logic.

**Comment by schokominzdrops** [comment]
I need measurements in rem for work: 10px = 1rem.
I installed an old version of the plugin now, so I can show you, what I mean.
I could choose Web View – CSS Rem, and then I changed the scale to 10.

<img width="307" alt="Bildschirmfoto 2020-11-05 um 12 04 14" src="https://user-images.githubusercontent.com/73957869/98236199-41237c00-1f63-11eb-8ffb-6c380fbabf2c.png">
<img width="238" alt="Bildschirmfoto 2020-11-05 um 12 32 14" src="https://user-images.githubusercontent.com/73957869/98236331-7c25af80-1f63-11eb-8d0f-72a49fd8da33.png">
<img width="236" alt="Bildschirmfoto 2020-11-05 um 12 32 24" src="https://user-images.githubusercontent.com/73957869/98236340-8051cd00-1f63-11eb-9413-47db3fd18e45.png">

**Comment by qjebbs** [comment]
I see. What you need is Unit convert ("unit switch" menu on top right), but no luck, `Rem 10px` is now not provided.

**Comment by qjebbs** [comment]
To not make things complicate, I just add a few units.
