### ISSUE TITLE
get Language error

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#47]
macOSVersion：10.15.5 
sysLanguage：zh-Hans-CN

macOSVersion 10.15.6
sysLanguage：zh-Hans

导致获取不到 i18n 对应的中文

**Comment by qjebbs** [comment]
Apple is so wild, but f184c0aa3e5927d789b80e34687356a26ccf4731 should fix it.😅

PS: 10.15.7 = zh-Hans-CN

**Comment by Ellean** [comment]
Still there.
Could you just make zh-Hans the fallback option?
