### ISSUE TITLE
Export via command line or node

### ISSUE THREAD

**Issue by mzehetho** [qjebbs/sketch-meaxure#49]
Hello,

I am searching for a way to generate a sketch export from a commited sketch file on my continuous integration system. I'm wondering if it would be possible to execute the export programmatically without sketch installed. A bonus would be if it would run on linux too.

Is this possible, or are you using sketchtool in the background, which only works on mac with sketch installed?

Thanks.

**Comment by qjebbs** [comment]
Yes, it only works on mac with sketch installed
