### ISSUE TITLE
如何正确使用第三方插件

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#5]
需求：我想使用第三方插件来做模板引擎，以支持快捷的导出其他文件，如dart文件
问题：只要使用npm install xxx ，然后npm run watch 都会报这些错误。

![image](https://user-images.githubusercontent.com/25951301/81796573-33ef7c80-9540-11ea-8c9d-f48ad2bd12a2.png)

**Comment by qjebbs** [comment]
I don't understand, in what scenario does this plugin require a dev dependency of template. I have no expertise on `art-template`, I'm afraid you have to figure it out by your self.

**Comment by uncleLian** [comment]
类似导出数据到template.html，但它是用简单的字符串替换进行传值。我的需求是导出其他后缀名的文件，所以需要更加灵活的模板去做替换，所以会用到第三方插件，如art-template。现在问题是安装任何插件，npm install xxx ，npm run watch都会出现上面的错误。

**Comment by qjebbs** [comment]
Cannot reproduce here, try `npm I`.

**Comment by qjebbs** [comment]
Closed due to no activities..
