### ISSUE TITLE
Specs from the toolbar: no variant in the Font-Face

### ISSUE THREAD

**Issue by stephanie-walter** [qjebbs/sketch-meaxure#58]
Hi,
First thanks for this alternative to measure this saves my current workflow.

I don't know if this is a bug or a technical limitation. But in the old measure, the specs would give the font variant (regular, bold, medium, etc.) In this version, it only gives the font name.

Current version (without the variant):
![image](https://user-images.githubusercontent.com/741338/103539951-3c167680-4e99-11eb-9bf4-9532769f27a8.png)

Previous "measure" version (with the variant):
![image](https://user-images.githubusercontent.com/741338/103540201-a9c2a280-4e99-11eb-9a8d-71a058f1766b.png)

Is it possible to bring back the font-variant (this is super useful for the dev team)

Note: the inspect specs export doesn't show the variant in the typeface list but you can see it in the CSS

![image](https://user-images.githubusercontent.com/741338/103544020-b77b2680-4e9f-11eb-9d3e-da9bc19d2ca1.png)

_Sketch Version 70.3 (109109)
Sketch Meaxure version: 3.3.4_

**Comment by siddharthksuri** [comment]
Quick question -
Big Sur. + Sketch 70.xx + Meaxure 3.3.4
Is the above a stable combination? 

Im on Catalina + Sketch 67 - so hopefully I can upgrade my OS & Sketchapp.

**Comment by qjebbs** [comment]
@stephanie-walter Yes, it's a technical limitation, Sketch is not providing it:

```ts
    console.log(
        text.style.fontFamily,
        text.style.fontSize,
        text.style.fontStretch,
        text.style.fontStyle,
        text.style.fontVariant,
        text.style.fontWeight,
    )
```
output:
```
Roboto 12 undefined undefined undefined 6
```

@siddharthksuri My expectation: It works
