### ISSUE TITLE
如何在 webStorm 成功编译出 sketch-meaxure.sketchplugin ？

### ISSUE THREAD

**Issue by violinday** [qjebbs/sketch-meaxure#59]
抱歉，我没有 typescript 和 webpack 开发经验。但是根据已有经验编写 ts 和 html 代码没问题。
想快速编译出插件文件进行功能验证。该如果做呢？
请问有编译步骤的说明吗？

或者编译步骤可以放在 README 文件中 : )

**Comment by qjebbs** [comment]
```
npm -i
npm run build
```
