### ISSUE TITLE
如何支持控件导出？原measure插件是支持的

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#6]
需求：有些时候需要支持控件的导出，以在标注页获得标注
问题：导出时没有控件选项

![image](https://user-images.githubusercontent.com/25951301/81931520-d7ae5a80-961c-11ea-97f3-c7a79e273f8f.png)

**Comment by qjebbs** [comment]
I hide them on purpose, to make the list tidy. It's rare to export symbols directly. If you still want to do so, organize them in an artboard, which is more friendly to developers.
