### ISSUE TITLE
Sketch crash after clicking on Toolbar or setting in menu in m1 MacBook ( Apple ARM architecture) 

### ISSUE THREAD

**Issue by tahamousavi** [qjebbs/sketch-meaxure#61]
After trying to open Toolbar or Setting, sketch crash immediately. But other features work finely.

Sketch 70.3

Model Name:	MacBook Air
Model Identifier:	MacBookAir10,1
Chip:	Apple M1
Total Number of Cores:	8 (4 performance and 4 efficiency)
Memory:	8 GB

**Comment by qjebbs** [comment]
Don't have m1 macbook, sorry. Can you debug on your own?

**Comment by tahamousavi** [comment]
It works finely on Sketch 70.4
