### ISSUE TITLE
How to build and run ?

### ISSUE THREAD

**Issue by forestlin1212** [qjebbs/sketch-meaxure#65]
How to build and run this project?  Sorry, I am not familiar with typescript.

**Comment by forestlin1212** [comment]
```
npm -i
npm run build
```
_Originally posted by @qjebbs in https://github.com/qjebbs/sketch-meaxure/issues/59#issuecomment-758381144_




Hi @qjebbs ,   I installed webpack v5.21.2,  and `npm run build` failed:

> const outputFileSystem = new webpack.MemoryOutputFileSystem()
                         ^
TypeError: webpack.MemoryOutputFileSystem is not a constructor
    at Object.<anonymous> (/Users/forest/Works/sketch-meaxure/scripts/buildTmpl.js:16:26)

I can't find clues about `MemoryOutputFileSystem` online.

**Comment by qjebbs** [comment]
try fetching latest commit

**Comment by forestlin1212** [comment]
> try fetching latest commit

Thanks, I wasn't familiar with webpack before,  installed webpack in the wrong path.  
I have now successfully built it in my fork. 

I made some modifications based on the needs of my project. 
Your code is really easy to maintain and very nice work. 👍👍👍
