### ISSUE TITLE
White border on right hand edge

### ISSUE THREAD

**Issue by ColinLondon** [qjebbs/sketch-meaxure#69]
When I export screens, some of them have a white border on the right edge. There seems to be no reason for it. I have even tried it on a blank artboard with background colour and still getting it.

Maybe I am using the wrong settings. Designing in 375*812

Puzzling.

**Comment by qjebbs** [comment]
need more info

**Comment by ColinLondon** [comment]
Sorry. I managed to resolve it but forgot to post back here. The error was at my end. Cheer.
