### ISSUE TITLE
标注位置识别错误

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#7]
问题：识别了隐藏图层的位置
期望：正确识别显示的图层
样本：[sample.zip](https://github.com/qjebbs/sketch-meaxure/files/4660292/sample.zip)

![image](https://user-images.githubusercontent.com/25951301/82515219-4d00ba80-9b4a-11ea-8305-15817a5d922c.png)

![image](https://user-images.githubusercontent.com/25951301/82516149-a10c9e80-9b4c-11ea-8854-627c41a1d481.png)

![image](https://user-images.githubusercontent.com/25951301/82516080-7f131c00-9b4c-11ea-977b-4f61d88691ef.png)

**Comment by qjebbs** [comment]
Should've fixed with 78ce60354be36e75f7029995ac2618914524c243
