### ISSUE TITLE
Can't check dp/sp in Android XHDPI@0.75x/2x/3x/4x  (new version)

### ISSUE THREAD

**Issue by toya2033** [qjebbs/sketch-meaxure#71]
Old version: choose _**Android device**_ → **_XHDPI @2x_**  → displayed in dp/sp
New version : choose _**Convert to pixel**_ → **_Android XHDPI @2x_** → displayed in px

Our Android programmer needs to check dp/sp in XHDPI@2x when programming, but the new version can only offer dp/sp in @1x(cannot offer in @0.75x/@2x/@3x/@4x ) , would you please fix this issue? 

Above all, we are very apprecate for you offering Meaxure!Thank you so much.

**Comment by qjebbs** [comment]
The latest release did change the convert logic, here it is:
1. Decide the design resolution in Sketch, e.g.: `1px` sketch = `1dp/sp` on device (the logic point, or fixed unit length)
2. when programming, use `pt` or `dp/sp`
3. If you want physical pixels in some cases, convert it from `64dp` to `128px` on XHDPI, which tells I need 128px of images for 64dp width in that device.

Tell me why it doesn't work for you.

**Comment by toya2033** [comment]
不知道中文描述是不是可以。
比如在sketch(版本72、默认1x)中有一个20x20(px)的矩形：
① 以前版本的meaxure导出的标注文件，选择安卓设备 → XHDPI@2X，这个矩形的高度显示为10dp；
② 现在版本的meaxure（3.3.4）导出的标注文件，选择切换设备 → 安卓设备-dp/sp，矩形的高度显示为20dp；如果选择 转换为像素值 → Android XHDPI@2x ，矩形的高度显示为40px。

我们的iOS研发查看没问题，但是安卓研发需要使用①中这种显示为10dp的转换方式，请问应该如何设置呢？

**Comment by qjebbs** [comment]
当你设计一个20x20（逻辑像素）的矩形的时候，表示在Android上是`20dp/sp`,在ios上是`20pt`，10dp从何而来呢（从设计意图上讲）？

听你的描述，感觉在ios上，这20是逻辑像素，在android上，20就变成物理像素了？

**Comment by toya2033** [comment]
是这样的，px与dp之间换算公式：dp=px*160/dpi。举个例子，设计师基于iphone6的设计稿标注20px，换算成dp就是20*160/320=20*(1/2)=20/2=10，也就是除以2得到10dp。
我前面回复中说的10dp指的是换算成安卓设备在XHDPI下的参数。Meaxure 3.2.9版本是可以实现这个转换查看的，3.3.4版本（或之间的某个版本）更新后去掉了刚才说的这种方式，所以想请问下是否有其他查看的途径，或者能否加回这种转换呢？

PS：非常感谢对Meaxure的研发和维护！

**Comment by qjebbs** [comment]
根据：`px与dp之间换算公式：dp=px*160/dpi`这句话，你的20px表示的是物理像素，即：你为了设计10dp的物体，用了20px的像素来展示，即，你是用2倍图做设计。

打开设置，选中 `XHDPI @2x`，告诉MeaXure 你是 2 倍图这个事实，导出后，默认的度量即是`10dp`，如果转换单位为px，开发者可以看到这个元素在XHDPI下实际的物理像素是20px

PS: MeaXure 推荐使用1倍图做设计

**Comment by toya2033** [comment]
好的，我理解了，新版本的转换逻辑跟以前不一样了，换一个逻辑就懂了，非常感谢耐心回复了半天！
