### ISSUE TITLE
sketch72版本导出symbol的时候崩溃

### ISSUE THREAD

**Issue by uncleLian** [qjebbs/sketch-meaxure#77]

**Comment by qjebbs** [comment]
try 72.1

**Comment by uncleLian** [comment]
[缺省图2.sketch.zip](https://github.com/qjebbs/sketch-meaxure/files/6458236/2.sketch.zip)

**Comment by uncleLian** [comment]
exportImage的时候崩溃了

**Comment by qjebbs** [comment]
good here on 10.15.7, it is maybe a os specific problem of sketch

**Comment by uncleLian** [comment]
10.15 和 11 一样会崩溃。只在72.1版本上发生

**Comment by qjebbs** [comment]
good here with  10.15.7+72.1, welcome PR since I cannot reproduce it.

**Comment by qjebbs** [comment]
duplicated with #78
