### ISSUE TITLE
MeaXure not working with Sketch 72.1

### ISSUE THREAD

**Issue by baakoo** [qjebbs/sketch-meaxure#78]
Hi, MeaXure is not running with Sketch 72.1. Export starts and after a few seconds Sketch crashes.
I can reproduce this issue on 3 or more Macs.

**Comment by qjebbs** [comment]
Welcome PR since I don't have mac 10.16 installed, and the issue is not reproduced in 10.15.7 & 72.1

**Comment by baakoo** [comment]
What can I do to help? It happens really on every mac- we have 5 incidents.

**Comment by qjebbs** [comment]
If you know coding, debug on your environment, and submit fixed code with PR; If not, wait for someone else do the job, or try  
 to find and use mac with 10.15 or an old version of Sketch .

**Comment by Wladi4** [comment]
Hey guys! Just update your Sketch App to 73th version and the plugin will start working again. Enjoy!

**Comment by hubzy** [comment]
There's nothing wrong with mine -v72.1

**Comment by JacqueH** [comment]
MeaXure 3.3.4 is working in a simple test with Sketch 74.1, OS X 10.15.7 (Catalina) on an early 2015 MacBook Air.

**Comment by baakoo** [comment]
Yes sorry für delay. Export ist working again
