### ISSUE TITLE
Question: Change colours of the info boxes/fonts

### ISSUE THREAD

**Issue by k4t0** [qjebbs/sketch-meaxure#9]
Hi, thanks for the plugin.
Is there a way to set the background colours  or the font color of the info boxes manually, even inside the plugin source code? I could not find the matching CSS attributes. Thanks you.

**Comment by qjebbs** [comment]
1. Inspect element with browser debug tool, to find out what style is assigned to it
1. Edit style section of exported `index.html` (line 8-200)

**Comment by k4t0** [comment]
Thanks for the answer. But I think I did not make my intention clear enough. I try to change the default background and font colours of the info bubbles, that the plugin creates. If I export an artboard, these boxes are part of the backgrounder image and can not be inspected.
I attached an image for a better explanation.
[https://ibb.co/d2Ncp4s](https://ibb.co/d2Ncp4s)

**Comment by qjebbs** [comment]
They're shared styles. Find & change them in Sketch, all styles in current document will be updated.

**Comment by k4t0** [comment]
Thank you. That helped a lot.
